// This property file was autogenerated by AutoSVA on 2023-09-09
// to check the behavior of the original RTL module, whose interface is described below: 

module fifo_prop
#(
		parameter ASSERT_INPUTS = 0,
		parameter INFLIGHT_IDX = 2,
		parameter SIZE = 4
)
(		// Clock + Reset
		input  wire                          clk,
		input  wire                          rst_n,
		input  wire                          in_val,
		input  wire                          in_rdy, //output
		input  wire [SIZE-1:0]               in_data,
		
		input  wire                          out_val, //output
		input  wire                          out_rdy,
		input  wire [SIZE-1:0]               out_data //output
	);

//==============================================================================
// Local Parameters
//==============================================================================

genvar j;
default clocking cb @(posedge clk);
endclocking
default disable iff (!rst_n);

// Re-defined wires 
wire [INFLIGHT_IDX-1:0] in_transid;
wire [INFLIGHT_IDX-1:0] out_transid;

// Symbolics and Handshake signals
wire [INFLIGHT_IDX-1:0] symb_in_transid;
am__symb_in_transid_stable: assume property($stable(symb_in_transid));
wire out_hsk = out_val && out_rdy;
wire in_hsk = in_val && in_rdy;

//==============================================================================
// Modeling
//==============================================================================

// Modeling incoming request for fifo
if (ASSERT_INPUTS) begin
	as__fifo_fairness: assert property (out_val |-> s_eventually(out_rdy));
end else begin
	am__fifo_fairness: assume property (out_val |-> s_eventually(out_rdy));
end

// Generate sampling signals and model
reg [3:0] fifo_transid_sampled;
wire fifo_transid_set = in_hsk && in_transid == symb_in_transid;
wire fifo_transid_response = out_hsk && out_transid == symb_in_transid;

always_ff @(posedge clk) begin
	if(!rst_n) begin
		fifo_transid_sampled <= '0;
	end else if (fifo_transid_set || fifo_transid_response ) begin
		fifo_transid_sampled <= fifo_transid_sampled + fifo_transid_set - fifo_transid_response;
	end
end
co__fifo_transid_sampled: cover property (|fifo_transid_sampled);
if (ASSERT_INPUTS) begin
	as__fifo_transid_sample_no_overflow: assert property (fifo_transid_sampled != '1 || !fifo_transid_set);
end else begin
	am__fifo_transid_sample_no_overflow: assume property (fifo_transid_sampled != '1 || !fifo_transid_set);
end


// Assert that if valid eventually ready or dropped valid
as__fifo_transid_hsk_or_drop: assert property (in_val |-> s_eventually(!in_val || in_rdy));
// Assert that every request has a response and that every reponse has a request
as__fifo_transid_eventual_response: assert property (|fifo_transid_sampled |-> s_eventually(out_val && (out_transid == symb_in_transid) ));
as__fifo_transid_was_a_request: assert property (fifo_transid_response |-> fifo_transid_set || fifo_transid_sampled);


// Modeling data integrity for fifo_transid
reg [SIZE-1:0] fifo_transid_data_model;
always_ff @(posedge clk) begin
	if(!rst_n) begin
		fifo_transid_data_model <= '0;
	end else if (fifo_transid_set) begin
		fifo_transid_data_model <= in_data;
	end
end

as__fifo_transid_data_unique: assert property (|fifo_transid_sampled |-> !fifo_transid_set);
as__fifo_transid_data_integrity: assert property (|fifo_transid_sampled && fifo_transid_response |-> (out_data == fifo_transid_data_model));

assign out_transid = fifo.buffer_tail_r;
assign in_transid = fifo.buffer_head_r;

//====DESIGNER-ADDED-SVA====//

// SVA property file for fifo module

// Property 1: If in_hsk is high, buffer head pointer should increment.
property pr__increment_head;
    @(posedge clk) 
    in_hsk |-> (fifo.buffer_head_r == $past(fifo.buffer_head_r) + 1);
endproperty
as__increment_head : assert property (pr__increment_head);

// Property 2: If out_hsk is high, buffer tail pointer should increment.
property pr__increment_tail;
    @(posedge clk) 
    out_hsk |-> (fifo.buffer_tail_r == $past(fifo.buffer_tail_r) + 1);
endproperty
as__increment_tail : assert property (pr__increment_tail);

// Property 3: If in_hsk is high, incoming data is stored at the head location.
property pr__store_data;
    @(posedge clk) 
    in_hsk |-> (fifo.buffer_data_r[fifo.buffer_head_r] == in_data);
endproperty
as__store_data : assert property (pr__store_data);

// Property 4: If out_hsk is high, data from tail of buffer is read.
property pr__read_data;
    @(posedge clk) 
    out_hsk |-> ($past(out_data) == fifo.buffer_data_r[$past(fifo.buffer_tail_r)]);
endproperty
as__read_data : assert property (pr__read_data);

// Property 5: out_val should be high if there's any valid data in the buffer.
property pr__output_valid;
    @(posedge clk) 
    |fifo.buffer_val_r |-> out_val;
endproperty
as__output_valid : assert property (pr__output_valid);

// Property 6: in_rdy should be low only if the buffer is full.
property pr__input_ready;
    @(posedge clk) 
    (&fifo.buffer_val_r) |-> (!in_rdy);
endproperty
as__input_ready : assert property (pr__input_ready);



endmodule